config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
	root "static#index"

  get "/contact" => "static#contact", as: "contact_index"

  # patch "/projects/done/:id" => "projects#done", as: :task_done

  resources :projects do
    resources :tasks, only: [:create, :update, :destroy]
    resources :discussions, only: [:create, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment

  validates :comment_id, uniqueness: {scope: :user_id}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment, :find_project

  def create
    @like = @comment.likes.new
    @like.user = current_user
    respond_to do |format|    
      if @like.save
        format.html{redirect_to @project, notice: "Liked"}
        format.js {render}
      else
        format.html{redirect_to @project, alert: "Unable to like this comment."}
        format.js {render}
      end
    end

  end

  def destroy
    @like = current_user.likes.find params[:id]
    respond_to do |format|
      if @like.destroy
        format.html{redirect_to @project, notice: "Un-liked"}
        format.js {render}
      else
        format.html{redirect_to @project, alert: "Unable to un-like this comment."}
        format.js {render}
      end
    end
    
  end

  private

  def find_comment
    @comment = Comment.find params[:comment_id]
  end

  def find_project
    @project = @comment.discussion.project
  end


end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes.html.slim
- if user_signed_in?
  - if comment.like_for(current_user).nil?
    = link_to "", comment_likes_path(comment), method: :post, class: "fa fa-thumbs-o-up like", remote: true
    br
  - else
    = link_to "", comment_like_path(comment, comment.like_for(current_user)), method: :delete, class: "fa fa-thumbs-up delete", remote: true
    br
- else 
  i.fa.fa-thumbs-o-up
p.likes-count = "#{comment.likes.count}"

app/views/likes/create.js.slim
| $("##{dom_id @comment} .like").html("#{j render partial: 'likes/likes', locals: {comment: @comment}}")

app/views/likes/destroy.js.slim
| $("##{dom_id @comment} .like").html("#{j render partial: 'likes/likes', locals: {comment: @comment}}")