config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
	root "static#index"

  get "/contact" => "static#contact", as: "contact_index"

  # patch "/projects/done/:id" => "projects#done", as: :task_done

  resources :projects do
    resources :tasks, only: [:create, :update, :destroy]
    resources :discussions, only: [:create, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  
end

app/views/shared/_footer.html.slim
footer.background
  .footer
    hr class="black-hr"
    p Contact: Adam Seckel || Address: 3890 West 24th Avenue, Vancouver, BC         

app/views/shared/_form.html.slim
= form_for @project do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: "form-control"

  .form-group
    = f.label :due_date
    br
    = f.datetime_select :due_date, class: "form-control"

  .modal-footer
    button.btn.btn-default data-dismiss="modal" type="button"  Close
    = f.submit class: "btn btn-primary"

app/views/shared/_nav.html.slim
  nav.navbar.navbar-default.bg-transition.navbar-fixed-top role="navigation" 
    
    .container-fluid
      
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li.nav-left
          li.special-align class=("#{'active' if request.path == '/projects'}") 
                = link_to "#{icon('th-list')} <span class='separator'> |</span> Projects".html_safe, projects_path
          li class=("#{'active' if request.path == '/'}") 
                = link_to "#{icon('compass')} <span class='separator'> |</span> Hanno".html_safe, root_path
          
          - if user_signed_in?
            li class=("#{'active' if request.path == new_user_session_path || request.path == user_session_path || request.path == edit_user_registration_path}") 
              = link_to "#{icon('user')} <span class='separator'> |</span> You".html_safe, edit_user_registration_path 
            li.nav-right
              = link_to "Logout", destroy_user_session_path, method: :delete
          
              
          - else
            li
              = link_to "#{icon('user')} <span class='separator'> |</span> Login".html_safe, new_user_session_path
            li.nav-right-extra

      