config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
	root "static#index"

  get "/contact" => "static#contact", as: "contact_index"

  # patch "/projects/done/:id" => "projects#done", as: :task_done

  resources :projects do
    resources :tasks, only: [:create, :update, :destroy]
    resources :discussions, only: [:create, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :comments, through: :discussions
  has_many :favourites, dependent: :destroy

  belongs_to :user
  
  scope :recent, -> { order("updated_at DESC") }

  def favourite_for (user)
    favourites.find_by_user_id user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @project = Project.new 
    @projects = Project.recent
  end

  def create
    @project = Project.new project_params
    @project.user = current_user
    if @project.save
      # flash[:notice] = "project saved successfully!"
      # # redirect_to question_path(@project)
      redirect_to @project
    else
      # flash.now[:alert] = "Please correct errors below"
      redirect_to root_path
    end
  end
  
  def show
    @project = Project.find params[:id]
    @task = Task.new
    @discussion = Discussion.new
    @comment = Comment.new

  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    if @project.update project_params
      redirect_to @project, notice: "Updated successfully!"
    else
      flash.now[:alert] = "Please correct errors below!"
      render :edit
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.destroy
      redirect_to projects_path
    else
      flash.now[:alert] = "Error"
      redirect_to @project
    end
    

  end


  private

  def project_params
    params.require(:project).permit(:title, :description, :due_date)
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper

  def done_tasks(project)
    @done = 0
    project.tasks.each do |task|
      if task.done 
        @done += 1
      end
    end
    return @done
  end

  def percent_done(project)
    @percent = done_tasks(project).to_f/project.tasks.count.to_f
    @percent = @percent * 100
    return @percent
  end

  def date_time(date)
  end


end

app/views/projects/edit.html.slim
=form_for @project do |f|
  .row
    .container-fluid.new-nav.new-nav-edit.fadeInDown.animated
      .container-fluid
        table.clearfix.special-forms
          tr
            td.special-padding
              = f.text_field :title, class: "form-control" 
            td.left
              h3 =link_to "Tasks (#{done_tasks(@project)}/#{@project.tasks.count})", project_path(anchor: "tasks")
            td.left
              h3 =link_to "Discussion (1)", project_path(anchor: "discussion")
            td.right.move-date 
              | Due:
              = f.datetime_select :due_date, class: "form-control"
            td.right.icon-link
              button.fa.fa-check.btn-default.btn type="submit"
        

  .row
    .image-content


  .container.project-content
    .col-md-12.description
      br
      p = f.text_area :description, class: "form-control"
      br
      
.row
  hr
.container.project-content    
  .col-md-12

  .row#accordian   
    .col-md-12.tasks 
      a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"
        .col-md-6.left
          h3#discussion Discussion (1)

    .col-md-12
      .container.collapse#collapseTwo
        .row
          .task.col-md-12
            br
            .container.margin-fix
              p 

             
          .task.col-md-12
            h4 Comments
            .container.margin-fix
              p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nullam quis risus eget urna mollis ornare vel eu leo.
  br
  .row#accordian
    .col-md-12.tasks.flip
      a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
        .col-md-6.left
          h3#tasks Tasks (#{done_tasks(@project)}/#{@project.tasks.count})

    .col-md-12
      .container.collapse#collapseOne
        -@project.tasks.each do |task|
          .task.col-md-6
            .col-md-1.status            
              -if !task.done 
                = link_to("", [@project, task], :method => :patch, class: "fa fa-square-o")
              - else
                = link_to("", [@project, task], :method => :patch, class: "fa fa-check-square-o")
              br
              = link_to "", [@project, task], :method => :delete, data:{confirm: "Are you sure?"}, class: "fa fa-times transition"
            .col-md-11
              h4 = task.title
              p = "Due: #{task.due_date}"
  br

         





  

app/views/projects/index.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#myModalLabel.modal-title Lets Start A New Project:
      .modal-body
	    	=render "shared/form"



.row
  a data-target="#myModal" data-toggle="modal" 
  	.col-md-12.start-something-new
        span.float-link-lighten.transition 
        h1 Start a New Project
        h2 Get on Course with Hanno

- if user_signed_in?
  - if current_user.favourite
    .container-fluid.index
      h1 Favourited Project
      .projects.col-md-12

        =link_to "", current_user.favourite.project, class: "float-link-lighten transition"
        .project.col-md-6.col-lg-6.col-sm-6.col-xs-6
          h3 =current_user.favourite.project.title
        .stats.col-md-6.col-lg-6.col-sm-6.col-xs-6
          h4 =current_user.favourite.project.due_date
          h4 #{current_user.favourite.project.tasks.count} Tasks / #{done_tasks(current_user.favourite.project)} Complete
          h4 #{current_user.favourite.project.comments.count} Comments

.container-fluid.index
  h1 ="#{@projects.count} Current Projects:"
  - @projects.each do |projects|

    .projects.col-md-12
      =link_to "", projects, class: "float-link-lighten transition"
      .project.col-md-6.col-lg-6.col-sm-6.col-xs-6
        h3 =projects.title
      .stats.col-md-6.col-lg-6.col-sm-6.col-xs-6
        h4 =projects.due_date
        h4 #{projects.tasks.count} Tasks / #{done_tasks(projects)} Complete
        h4 #{projects.comments.count} Comments

/ section for completed projects

app/views/projects/show.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#myModalLabel.modal-title New Task:
      .modal-body
        = form_for [@project, @task] do |f|
          .form-group
            = f.label :title
            = f.text_field :title, class: "form-control"

          .form-group
            = f.label :due_date
            br
            = f.datetime_select :due_date, class: "form-control"

          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Close
            = f.submit class: "btn btn-primary"

#discussion-modal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
          span.sr-only Close
        h4#myModalLabel.modal-title New Discussion Topic:
      .modal-body
        = form_for [@project, @discussion] do |f|
          .form-group
            = f.label :title
            = f.text_field :title, class: "form-control"

          .form-group
            = f.label :discussion
            br
            = f.text_area :description, class: "form-control"

          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Close
            = f.submit class: "btn btn-primary"

.row
  .container-fluid.new-nav.fadeInDown.animated
    .container-fluid
      table.clearfix
        tr
          td
            h1 =@project.title.truncate(50) 
          td.left
            h3 =link_to "Tasks (#{done_tasks(@project)}/#{@project.tasks.count})", project_path(anchor: "tasks")
          td.left
            h3 =link_to "Discussions (#{@project.discussions.count})", project_path(anchor: "discussion")
          td.right
            h3 ="#{@project.due_date.strftime("Due on %m/%d/%Y at %I:%M%p")}"
          td.right.icon-link
            a =link_to "", edit_project_path(@project), class: "fa fa-cog like"
          - if user_signed_in? && current_user == @project.user
            td.right.icon-link
              a = link_to "", project_path(@project), method: :delete, data:{confirm: "Are you sure you want to delete this project?"}, class: "fa fa-times delete"
          td.right.icon-link
            - if user_signed_in?
              - if @project.favourite_for(current_user).nil?
                = link_to "", project_favourites_path(@project), method: :post, class: "fa fa-bookmark-o bookmark"
              -else 
                = link_to "", project_favourite_path(@project, @project.favourite_for(current_user)), method: :delete, class: "fa fa-bookmark delete"
        tr
          td colspan="7"
            .progress
              .progress-bar.progress-bar-info.active.progress-bar-striped aria-valuemax="#{@project.tasks.count}" aria-valuemin="0" aria-valuenow="#{done_tasks(@project)}" role="progressbar" style=("width: #{percent_done(@project)}%;") 
                span.sr-only 0% Complete

.row
  .image-content


.container.project-content
  .col-md-12.description
    br
    p = "Description: #{@project.description}"
    br
.row
  hr
.container.project-content    
  .col-md-12

  .row#accordian   
    .col-md-12.tasks 
      a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"
        .col-md-6.left
          h3#discussion = "Discussions (#{@project.discussions.count})"
        .col-md-6.right
          a data-target="#discussion-modal" data-toggle="modal" 
            i.fa.fa-plus.fa-1x.transition
    .col-md-12
      .container.collapse.in#collapseTwo
        -@project.discussions.each do |discussion|
          .col-md-12.discussion
            .container
              table.table-full-width
                tr
                  td.status-padding
                    - if user_signed_in? && current_user == discussion.user
                      = link_to "", [@project, discussion], :method => :delete, data:{confirm: "Are you sure?"}, class: "fa fa-times delete"
                  td
                    h3 =discussion.title
                tr
                  td
                  td
                    blockquote =discussion.description
                tr
                  td
                  td
                    h4 Comments
                    table.comments.table-full-width-2 id=dom_id(discussion)
                      -discussion.comments.each do |comment|
                        = render(partial: "/comments/comment", locals: {comment: comment, discussion: discussion})
                tr
                  td
                  td.comment
                    .new-comment= render(partial: "/comments/form", locals: {discussion: discussion, comment: @comment})

  br
  .row#accordian
    .col-md-12.tasks.flip
      a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
        .col-md-6.left
          h3#tasks Tasks (#{done_tasks(@project)}/#{@project.tasks.count})
        .col-md-6.right
          a data-target="#myModal" data-toggle="modal" 
            i.fa.fa-plus.fa-1x.transition
    .col-md-12
      .container.collapse.in#collapseOne
        -@project.tasks.each do |task|
          .task.col-md-6
            .col-md-1.status            
              -if !task.done 
                = link_to "", [@project, task], :method => :patch, class: "fa fa-square-o transition mark-task"
              - else
                = link_to "", [@project, task], :method => :patch, class: "fa fa-check-square-o transition delete"
              br
              - if user_signed_in? && current_user == task.user
                = link_to "", [@project, task], :method => :delete, data:{confirm: "Are you sure?"}, class: "fa fa-times delete"
            .col-md-11
              h4 = task.title
              p = "Due: #{task.due_date}"
  br

  